app_admin/urls.py
# coding: utf-8
from django.conf.urls import include, url
from django.contrib import admin
from app_admin import views


urlpatterns = [
    url(r'^$', views.AdminIndexPage.as_view(), name='pythonix_admin'),
    url(r'^create_client/$', views.CreateClient.as_view(), name='create_client'),
    url(r'^client_info/(?P<pk>\d+)/$', views.ClientInfoView.as_view(), name='client_info'),
    url(r'^clients_list/(?P<pk>\d+)/$', views.ClientsList.as_view(), name='clients_list'),
    url(r'^del_client/(?P<pk>\d+)/$', views.ClientDelete.as_view(), name='del_client'),

    url(r'^get_free_ipaddress/(\d{1,9})/$', views.get_free_ipaddress, name='get_free_ipaddress'),
    url(r'^get_client_groups/(\d{1,9})/$', views.get_client_groups, name='get_client_groups'),
    url(r'^abbreviation_physical_network/(\d{1,9})/$', views.abbreviation_physical_network, name='abbreviation_physical_network'),
    url(r'^update_password/(\d{1,9})/$', views.update_password, name='update_password'),
    url(r'^pay_balance/(\d{1,9})/(\d{1,9})/$', views.pay_balance, name='pay_balance'),
    url(r'^client_on_off/(\d{1,9})/(\d{1,9})/$', views.client_on_off, name='client_on_off'),
    url(r'^send_sms_info_client_ajax/(\d{1,9})/(\d{1,9})/$', views.sendSmsInfoClientAjax, name='send_sms_info_client_ajax'),
    url(r'^get_status_client/(\d{1,9})/$', views.getStatusClient, name='get_status_client'),
    url(r'^report_pay_admin_list/$', views.ReportPayAdminList.as_view(), name='report_pay_admin_list'),
]

pythonix/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Examples:
    url(r'^$', 'app_admin.views.admin_index', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^pythonix_admin/', include('app_admin.urls', app_name='pythonix_admin', namespace='pythonix_admin')),
    url(r'^pythonix_client/', include('app_client.urls', app_name='pythonix_client', namespace='pythonix_client')),
]

app_admin/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User, UserManager
from django.contrib.auth.hashers import make_password
from django.utils.crypto import get_random_string

import random
import datetime

import app_scripts.tarifs_mikrotik


class AdminProfile(User):
    objects = UserManager()

    permissions = (
        (1, 'All action'),
        (2, 'See, Add, Edit, Del  Clients'),
        (3, 'See Report'),
        (4, 'Generated card'),
        (5, 'See client')
        )

    admin_status = models.BooleanField(verbose_name='Статус администратора', default=True)
    permissions_role = models.IntegerField(verbose_name='Выбор привелегий доступа', default=1, choices=permissions)


    class Meta:
        verbose_name = u'Профиль администратора'
        verbose_name_plural = u'Профили администраторов'
        db_table = "admin_profile"


    def __unicode__(self):
        return '{}'.format(self.username)


# Физическая сеть
class PhysicalNetwork(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название физической сети')
    select_admin = models.ManyToManyField(User, verbose_name='Выбор администратора')
    abbreviation = models.CharField(max_length=150, verbose_name='Аббревиатура физической сети')
    channel_width = models.IntegerField(verbose_name='Ширина канала', blank=True)

    class Meta:
        verbose_name = u'Физическая сеть'
        verbose_name_plural = u'Физические сети'
        db_table = 'physical_network'

    def __unicode__(self):
        return u'{}'.format(self.name)


# Сервера
class Servers(models.Model):
    SERVER_OS = (
        (1, 'MikroTik RouterOS'),
    )

    title = models.CharField(max_length=150, verbose_name='Название Сервера')
    physical_network = models.ForeignKey(PhysicalNetwork, verbose_name='Выбор физической сети')
    device_type = models.IntegerField(verbose_name='Выбор операционной системы', default=1, choices=SERVER_OS)
    network_address = models.GenericIPAddressField(verbose_name='Сетевой адрес устройства')
    login = models.CharField(max_length=50, verbose_name='Логин для доступа к устройству')
    password = models.CharField(max_length=50, verbose_name='Пароль для доступа к устройству')
    api_port = models.IntegerField(verbose_name='API порт', default=8728)
    status_on_off = models.BooleanField(verbose_name='Состояние работы сервера', default=True)

    class Meta:
        verbose_name = u'Сервер'
        verbose_name_plural = u'Сервера'
        db_table = 'device'

    def __unicode__(self):
        return u'{}'.format(self.title)


# IP Подсети v4
class IPV4Networks(models.Model):

    MASK_CHOICES = (
    (1, '1'),(2, '2'),(3, '3'),(4, '4'),(5, '5'),(6, '6'),(7, '7'),(8, '8'),(9, '9'),(10, '10'),(11, '11'),
    (12, '12'),(13, '13'),(14, '14'),(15, '15'),(16, '16'),(17, '17'),(18, '18'),(19, '19'),(20, '20'),
    (21, '21'),(22, '22'),(23, '23'),(24, '24'),(25, '25'),(26, '26'),(27, '27'),(28, '28'),(29, '29'),
    (30, '30'),(31, '31'),(32, '32'),
    )

    ipv4networks = models.GenericIPAddressField(verbose_name='IP Подсети')
    CIDR = models.IntegerField(choices=MASK_CHOICES, default=24)

    class Meta:
        verbose_name = u"Подсеть IPv4"
        verbose_name_plural = u'Список подсетей IPv4'
        db_table = "ip_v4_networks"

    def __unicode__(self):
        return u'{}'.format(self.ipv4networks)


# Группы клиентов
class ClientsGroups(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название группы')
    ipv4networks_list = models.ManyToManyField(IPV4Networks, verbose_name='Список подсетей IPv4')
    select_admin = models.ManyToManyField(User, verbose_name='Выбор администратора')
    select_server = models.ForeignKey(Servers, verbose_name='Выбор сервера')

    class Meta:
        verbose_name = u'Группа клиентов'
        verbose_name_plural = u'Группы клиентов'
        db_table = 'clients_groups'

    def __unicode__(self):
        return u'{}'.format(self.title)


# Тарифы
class Tarifs(models.Model):
    UNIT_SPEED = (
    ('k', 'k'),('M', 'M'),
    )

    select_physicalnetwork = models.ForeignKey(PhysicalNetwork, verbose_name='Выбор физической сети')
    title = models.CharField(max_length=150, verbose_name='Название тарифа')
    speed_up = models.IntegerField(verbose_name='Исходящая скорость, значение')
    speed_down = models.IntegerField(verbose_name='Входящая скорость, значение')
    speed_up_unit = models.CharField(max_length=1, verbose_name='Исходящая скорость, единица измерения', choices=UNIT_SPEED)
    speed_down_unit = models.CharField(max_length=1, verbose_name='Входящая скорость, единица измерения', choices=UNIT_SPEED)
    price = models.IntegerField(verbose_name='Абонплата')
    speed_limit = models.BooleanField(verbose_name='Лимитирование скорости', default=False)
    limit_rule = models.CharField(max_length=200, verbose_name='Правило, лимита', blank=True, null=True,)
    add_rule_in_device = models.BooleanField(verbose_name='Создавать ли правила в устройстве', default=True)

    class Meta:
        verbose_name = u'Тариф'
        verbose_name_plural = u'Тарифы'
        db_table = 'tarifs'

    def __unicode__(self):
        return u'{}'.format(self.title)

    def get_actions(self, request):
        actions = super(Tarifs, self).get_actions(request)
        if 'delete_selected' in actions:
            del actions['delete_selected']
        return actions

    def save(self, *args, **kwargs):
        super(Tarifs, self).save(*args, **kwargs)
        for server in Servers.objects.filter(physical_network=self.select_physicalnetwork):
            app_scripts.tarifs_mikrotik.createTarifAddQueue(server.network_address, server.api_port,
                server.login, server.password, self.speed_up, self.speed_up_unit, self.speed_down, self.speed_down_unit)


    def delete(self, using=None):
        for server in Servers.objects.filter(physical_network=self.select_physicalnetwork):
            app_scripts.tarifs_mikrotik.deleteTarifAndQueue(server.network_address, server.api_port,
                server.login, server.password, self.speed_up, self.speed_up_unit, self.speed_down, self.speed_down_unit)
        super(Tarifs, self).delete(using)




# Улицы
class Streets(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название улицы')
    select_physical_network = models.ForeignKey(PhysicalNetwork, verbose_name='Выбор физической сети')


    class Meta:
        verbose_name = u'Улицу'
        verbose_name_plural = u'Улицы'
        db_table = 'streets'

    def __unicode__(self):
        return u'{}'.format(self.title)


# Клиенты
class Clients(User):
    objects = UserManager()

    ip_address = models.GenericIPAddressField(verbose_name='IP адрес клиена')
    ipv6_address = models.GenericIPAddressField(verbose_name='IPv6 адрес клиена', default="2001:0db8:11a3:09d7:1f34:8a2e:07a0:765d")
    send_sms = models.BooleanField(verbose_name='Желание получать смс', default=False)
    select_tarif = models.ForeignKey(Tarifs, verbose_name='Выбор тарифа')
    select_clients_group = models.ForeignKey(ClientsGroups, verbose_name='Выбор группы клиентов')
    create_date = models.DateField(verbose_name='Дата подключения', auto_now_add=True)
    end_used_date = models.DateField(verbose_name='Дата окончяния услуги', default=(datetime.datetime.now() + datetime.timedelta(days=7)))
    select_street = models.ForeignKey(Streets, verbose_name='Выбор улицы')
    mobile_phone = models.CharField(max_length=50, verbose_name='Мобильный телефон', blank=True, null=True,)
    home_address = models.CharField(max_length=50, verbose_name='Домашний адрес', blank=True, null=True,)
    network_traffic_per_day = models.IntegerField(verbose_name='Сетевой трафик за день', null=True, default=0)
    network_traffic_for_the_month = models.IntegerField(verbose_name='Сетевой трафик за месяц', null=True, default=0)
    balance = models.IntegerField(verbose_name='Баланс', default=0)
    internet_status = models.BooleanField(verbose_name='Статус клиента, доступ разрешен/запрещен', default=1)
    error_card = models.IntegerField(verbose_name='Ошибки пополнения карточкой', null=True, default=0)
    deleted_user = models.BooleanField(default=False, verbose_name='Статус удаления пользователя')
    key = models.CharField(max_length=50, default="000000000")

    class Meta:
        verbose_name = u"Клиент"
        verbose_name_plural = u"Клиенты"
        db_table = "clients"

    def __unicode__(self):
        return u'{} {} {} {} {}'.format(self.first_name, self.last_name, self.select_clients_group, self.ip_address, self.deleted_user)


# Модель отчета пополнений администраторами
class ReportPayAdmin(models.Model):
    id_admin_select = models.ForeignKey(AdminProfile, verbose_name='Выбор Администратора')
    id_client_select = models.ForeignKey(Clients, verbose_name='Выбор Клиента')
    sum = models.IntegerField(verbose_name='Сумма пополнения')
    date_of_refill = models.DateField(verbose_name='Дата пополнения', auto_now_add=True)

    class Meta:
        verbose_name = u"Пополнение администратором"
        verbose_name_plural = u"Пополнение администратором"
        db_table = "report_pay_admin"

    def __unicode__(self):
        return u'{} {} {} {}'.format(self.id_admin_select.first_name,
                                     self.id_client_select.first_name, self.sum, self.date_of_refill)


# Временные платежи
#class TemporaryPayment(models.Model):
#    select_client = models.ForeignKey(Clients, verbose_name='Выбор клиента')
#    sum = models.IntegerField(verbose_name='Сумма пополнения')
#    namber_days = models.IntegerField(verbose_name='Количество дней')
#    date_of_create = models.DateField(verbose_name='Дата создания платежа')
#    status = models.BooleanField(verbose_name='Состояние временного платежв', default=True)

#    class Meta:
#        verbose_name = u"Временный платеж"
#        verbose_name_plural = u"Временные платежи"

app_admin/forms.py
# coding: utf-8
from django import forms

from captcha.fields import CaptchaField


class DelClientForm(forms.Form):

    captcha = CaptchaField()

app_admin/templates/app_admin/clients_list.html
{% extends 'app_admin/base.html' %}
{% load staticfiles %}
{% block css_block %}
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables/dataTables.bootstrap.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static "dist/css/skins/_all-skins.min.css" %}">
{% endblock %}

{% block Content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Список клиентов
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">{{ clients_group }} {{ clients_list.count }}</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Адрес</th>
                        <th>Баланс</th>
                        <th>Дата отключения</th>
                        <th>Тариф</th>
                        <th>Действия</th>
                      </tr>
                    </thead>
                    <tbody>


                      {% for client in clients_list %}
                      <tr>
                        <th>{{ client.select_street.title }} {{ client.home_address }}</th>
                        <th>{{ client.balance }}</th>
                        <th>{{ client.end_used_date }}</th>
                        <th>{{ client.select_tarif.title }}</th>
                        <th><a href="{% url 'pythonix_admin:client_info' client.id %}"><button class="btn btn-block btn-default">Инфо</button></a></th>
                      </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>

                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div>

{% endblock %}


{% block js_block %}
     <!-- jQuery 2.1.4 -->
    <script src="{% static "plugins/jQuery/jQuery-2.1.4.min.js" %}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <!-- DataTables -->
    <script src="{% static "plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "plugins/datatables/dataTables.bootstrap.min.js" %}"></script>
    <!-- SlimScroll -->
    <script src="{% static "plugins/slimScroll/jquery.slimscroll.min.js" %}"></script>
    <!-- FastClick -->
    <script src="{% static "plugins/fastclick/fastclick.min.js" %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static "dist/js/app.min.js" %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static "dist/js/demo.js" %}"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock %}

app_admin/templates/app_admin/create_client.html
{% extends 'app_admin/base.html' %}
{% load cms %}
{% block Content %}
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Создание клиента
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Форма создания клиента</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                 <form method="POST" class="b-form" name="add_client_form" id="resume-form" enctype="multipart/form-data" action="{% url 'pythonix_admin:create_client' %}">
                     {% csrf_token %}
                  <div class="box-body">
                    <div class="form-group">
                      <label>Выбор сети</label>
                      <select class="form-control" id="physical_networks" name="name_physical_networks">
                            <option value="">Выбрать сеть</option>
                          {% for physical_network in physical_networks %}
                            <option value="{{ physical_network.id }}">{{ physical_network.name }}</option>
                          {% endfor %}
                      </select>
                    </div>
                    {% lite_include 'app_admin/__includes/form_fields/select.html' field=form.select_clients_group %}

                      <!-- Список свободных ip -->
                    <div class="form-group">
                      <label>Выбор свободного IP</label>
                      <select class="form-control" id="select_ip" name="name_select_ip">
                      </select>
                    </div>
                    {% lite_include 'app_admin/__includes/form_fields/input_ipv4_address.html' field=form.ip_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.ipv6_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.username %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.first_name %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.last_name %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.email %}
                    {% lite_include 'app_admin/__includes/form_fields/radio.html' field=form.send_sms %}
                    {% lite_include 'app_admin/__includes/form_fields/select.html' field=form.select_tarif %}
                    {% lite_include 'app_admin/__includes/form_fields/select.html' field=form.select_street %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.mobile_phone %}
                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.home_address %}
                    {% lite_include 'app_admin/__includes/form_fields/input_balance.html' field=form.balance %}



                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </form>
              </div><!-- /.box -->



            </div><!--/.col (left) -->


          </div>   <!-- /.row -->
        </section><!-- /.content -->
      </div>
{% endblock %}

{% block js_block %}
    {{ block.super }}
    <script type="application/javascript">

        // Выбор группы клиентов из списка
        $('#id_select_clients_group').change(function() {
            var client_group = $("select#id_select_clients_group").val();
            var page_url = '/pythonix_admin/get_free_ipaddress/' + client_group + '/';
            $.get(page_url, function(data) { //Выполняем запрос на получение списка свободных ip.

                    var text = "<option value=''>Выберите ip адрес</option>";
                    for (var i in data) {  //Наполняем список элементами.
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;

                    }
                    document.add_client_form.select_ip.innerHTML = text;
                });
        });

        // Выбор свободного ip адреса
        $('#select_ip').change(function() {
            var free_ip = $("select#select_ip").val();
            $('#id_ip_address').val(free_ip);
        });

        // Выбор физической сети
        $('#physical_networks').change(function() {
            var physical_network = $("select#physical_networks").val();
            var page_url = '/pythonix_admin/abbreviation_physical_network/' + physical_network + '/';
            if (physical_network != ""){
                // Получаем абривиатуру выбранной сети
                $.get(page_url, function(data) {
                    $('#id_username').val(data['abbreviation']+'_');
                });


                // Список групп клиентов, выбранной сети
                var page_url = '/pythonix_admin/get_client_groups/' + physical_network + '/';
                $.get(page_url, function(data) {
                    var text = "<option value=''>Выберите группу клиентов</option>";
                    for (var i in data) {
                        add_element = "<option value="+i+">"+data[i]+"</option>";
                        text += add_element;

                    }
                    document.add_client_form.select_clients_group.innerHTML = text;
                });
            }

        });
    </script>
{% endblock %}

app_admin/templates/app_admin/delete_client.html
{% extends 'app_admin/base.html' %}
{% load cms %}
{% block Content %}
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Удалить клиента
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <!-- general form elements -->
              <div class="box box-default">
                <div class="box-header with-border">
                  <h3 class="box-title">Форма удаления клиента</h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                 <form method="POST" class="b-form" name="add_client_form" id="resume-form" enctype="multipart/form-data" action="{% url 'pythonix_admin:del_client' client_id %}">
                     {% csrf_token %}
                  <div class="box-body">

                    {% lite_include 'app_admin/__includes/form_fields/input_text.html' field=form.captcha %}

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="submit" class="btn btn-danger">Удалить</button>
                  </div>
                </form>
              </div><!-- /.box -->



            </div><!--/.col (left) -->


          </div>   <!-- /.row -->
        </section><!-- /.content -->
      </div>
{% endblock %}

app_admin/templates/app_admin/report_pay_list.html
{% extends 'app_admin/base.html' %}
{% load staticfiles %}
{% block css_block %}
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static "plugins/datatables/dataTables.bootstrap.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static "dist/css/skins/_all-skins.min.css" %}">
{% endblock %}

{% block Content %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Отчет о пополнениях клиентов
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <div class="col-xs-12">


              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">{{ clients_group }} {{ clients_list.count }}</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Клиент</th>
                        <th>Администратор</th>
                        <th>Сумма</th>
                        <th>Дата</th>
                      </tr>
                    </thead>
                    <tbody>


                      {% for pay in report_pay_list %}
                      <tr>
                        <th>{{ pay.id_client_select.select_street.title }} {{ pay.id_client_select.home_address }}</th>
                        <th>{{ pay.id_admin_select.first_name }} {{ pay.id_admin_select.last_name }}</th>
                        <th>{{ pay.sum }}</th>
                        <th>{{ pay.date_of_refill }}</th>
                      </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>

                    </tfoot>
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
      </div>

{% endblock %}


{% block js_block %}
     <!-- jQuery 2.1.4 -->
    <script src="{% static "plugins/jQuery/jQuery-2.1.4.min.js" %}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <!-- DataTables -->
    <script src="{% static "plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "plugins/datatables/dataTables.bootstrap.min.js" %}"></script>
    <!-- SlimScroll -->
    <script src="{% static "plugins/slimScroll/jquery.slimscroll.min.js" %}"></script>
    <!-- FastClick -->
    <script src="{% static "plugins/fastclick/fastclick.min.js" %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static "dist/js/app.min.js" %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static "dist/js/demo.js" %}"></script>
    <!-- page script -->
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
{% endblock %}